const defaultQuotes = [
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
  "Verily, with hardship, there is relief",
  "And whoever puts their trust in Allah, then He will suffice him",
  "Do not despair, for Allah is with those who have patience",
  "Trust in Allah's plan for you, for He knows what is best",
  "Allah understands our prayers even when we can't find the words to say Them",
  "Tawakkul is having full faith that ALLAH will take care of you even when things look Impossible",
  "Islam is not about, 'We are better than you'. Islam is about 'Let me show you something that is better for you",
  "The overly jealous seek to harm and hurt others, but in the end, only harm themselves",
  "O you who believe! seek help through patience and prayers indeed, Allah is with the patient",
  "Patience is beautiful... When you feel vulnerable and alone, just remember that His canopy is always above you... Always... La Hawla Wala Quwwata Illah Billah...",
  "Worldly life is short, so turn to Allah before you return to Allah",
  "There is reward for Kindness to every living thing",
  "Be somebody in the eyes of ALLAH, even if you are nobody in the eyes of people",
  "Born from different mothers skins of all colors come together as brothers. that's the beauty of Islam",
  "No one besides Allah can rescue a soul from hardship",
  "Indeed, the patient will be given their reward without account",
  "Indeed, Allah loves those who are constantly repentant and loves those who purify themselves",
  "No calamity befalls Anyone except by Allah's will; courage is fear that has said its prayers",
];

window.onload = function () {
  main();
};

// references

function main() {
  const newQuoteBtn = document.getElementById("new-quote-btn");
  const quoteBody = document.getElementById("quote-body");

  newQuoteBtn.addEventListener("click", function () {
    const index = Math.floor(Math.random() * 100);
    const quote = defaultQuotes[index];
    quoteBody.innerText = quote;
  });
}
